### ISSUE TITLE
[BUG/ISSUE] Native mode not working wirelessly outside of steam 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#13]
**Describe the bug**

**To Reproduce**
1. Game pad tester or
2. Launch game 
3.controller not detected wirelessly outside of steam

**Comment by Paliverse** [comment]
No notice of this issue, Controller is always visible once Native Mode becomes active.

**Comment by popthemoff** [comment]
So tell me why when connected wireless then gamepad tester does not
recognise controller in native mode
