### ISSUE TITLE
Player LEDs not showing

### ISSUE THREAD

**Issue by XDanfr** [Paliverse/DSX#15]
Since setup I've been having this issue. Here's the log file. I am wired btw
[dsx-20230711.log](https://github.com/Paliverse/DSX/files/12016403/dsx-20230711.log)
[dsx-20230711_001.log](https://github.com/Paliverse/DSX/files/12016404/dsx-20230711_001.log)
[dsx-20230711_002.log](https://github.com/Paliverse/DSX/files/12016405/dsx-20230711_002.log)
(not sure why there are 3 but they're all today, all different)

**Comment by XDanfr** [comment]
Just realised this only happens in 360 mode btw

**Comment by popthemoff** [comment]
I can confirm that this happens to me too when connected via USB, Bluetooth seems ok (Popbot)

**Comment by Paliverse** [comment]
Has been fixed.
