### ISSUE TITLE
[BUG/ISSUE] Dualsense emulation not passing regular rumble to controller in many native supported games 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#16]
**Describe the bug**
Some native games don't pass rumble to controller like they would if played with Xbox emulation. Not sure if this is by game design. I understand that haptics would be missing.
**To Reproduce**
1. Play native supported games with Dualsense emulation, then do same test with Xbox emulation  F122, Deathloop, A plague tales requiem, Scars above 
2. Returnal 
3.farcry 6

**Comment by popthemoff** [comment]
Seems that some games switch between exclusive haptics mode when Dualsense emulation is active and no other solution would be possible at this time?

**Comment by Paliverse** [comment]
I think this all depends on if the native game supports a back up system that reverts to normal rumble, I will have to look at the code as well to make sure if there is rumble being passed through but not being applied. I haven’t had a chance the past few days to really test.
