### ISSUE TITLE
[BUG/ISSUE] Removing a HDD with some of the steam games

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#20]
**Describe the bug**
I recently moved some games to a external HDD, I have removed the HDD and now the library doesn't populate any games, I still have games on other SSD drives.

**To Reproduce**
1. 
2. 
3.

**Comment by Execrit** [comment]
how is that related to DSX

**Comment by popthemoff** [comment]
> how is that related to DSX

This is where V3 alpha testing bugs are reported, so yes it's related

**Comment by Execrit** [comment]
ah I thought you were talking about steam library lol

**Comment by popthemoff** [comment]
> ah I thought you were talking about steam library lol

I was, within the DSX V3 UI, check out DSX discord and channel DSX preview 
https://discord.com/channels/836790685784211486/846614435308634122/1069880413289467928

**Comment by popthemoff** [comment]
Fixed with library UI update 108?
