### ISSUE TITLE
[BUG/ISSUE] Native emulation removes controller from hidhide hidden device list 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#21]
**Describe the bug**
Switching from any emulation will remove controller from list

**To Reproduce**
1. 
2. 
3.

**Comment by Paliverse** [comment]
This is normal so that it's visible to other apps/applications.

**Comment by popthemoff** [comment]
Oh ok I shall close the post, still the issue of native not working
wirelessly outside of steam?

**Comment by popthemoff** [comment]
This was intended
