### ISSUE TITLE
[BUG/ISSUE] Trigger vibration weak when wired 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#22]
**Describe the bug**
Adaptive triggers have a weak vibration compared to Bluetooth 

**To Reproduce**
1. 
2. 
3.

**Comment by Paliverse** [comment]
I have tested this in v2 and even much older builds of v3, and they all have the same feeling of strength. So i don't think anything can be done about this. I beleive it's weaker by default due to the microphone being exposed since the controller is connected wired.
