### ISSUE TITLE
[BUG/ISSUE] Adaptive triggers 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#23]
**Describe the bug** Reported by (XDan ) if on startup you're on X360 mode then no triggers work, switch to any other and they work then switch back to Xbox and they stay but can't be changed unless you switch modes to something other than Xbox mode
(WIRED ONLY)
**To Reproduce**
1. 
2. 
3.

**Comment by Paliverse** [comment]
Has been fixed for the next alpha version not released yet
