### ISSUE TITLE
[BUG/ISSUE] Audio haptics 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#25]
**Describe the bug** when two audio sources are available in windows, switching between them turns off the haptics, the only way to then get it working is to unplug cable to controller and reconnect 

**To Reproduce**
1. Use audio haptics 
2. Switch between speakers and headphones or vice versa for my example 
headphones are 2.4ghz Sony wireless and external speakers get sound via HDMI to monitor and digital out to soundbar

**Comment by Paliverse** [comment]
Just Fixed, coming in Alpha 102

**Comment by popthemoff** [comment]
I don't think 102 fixed this. I will test again later. 26/09/23

Doesn't seem to want to auto switch like V2 does. I have to faff about with the mixer if I change between audio devices

**Comment by Paliverse** [comment]
Odd, in my testing it works when i switch the default sound device to something else. it restarts.

**Comment by popthemoff** [comment]
Working when mixer is left at default for all audio source
