### ISSUE TITLE
[BUG/ISSUE] Infinite loading at first launch

### ISSUE THREAD

**Issue by GuckicheLorraine** [Paliverse/DSX#26]
**Describe the bug** DSX loads infinitely once the setup is done at first launch.

**To Reproduce**
1. Install DSX
2. Launch it for the first time
3. Setup DSX
4. have fun with infinite loading

If you force the program to stop and launch it again, it opens without any problem.

**Comment by Paliverse** [comment]
I think this should be resolved as I don’t see any other mentions of this.
