### ISSUE TITLE
[BUG/ISSUE] All Emulations & audio haptics 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#27]
**Describe the bug**
When playing game with any emulation and audio haptics the games vibration is not passed to controller, working in native mode only 
Will update if necessary , I have checked that rumble is active 

**To Reproduce**
1. Select emulation and audio haptics 
2. Play game 
3.

**Comment by Paliverse** [comment]
Implemented Rumble Passthrough toggles in Alpha 102 for 

- Audio To Haptics 
- Button To Haptics
- Trigger To Haptics
- Joystick To Haptics

You will find the toggle in each haptic mode properties section

All are toggled on by default.

**Comment by popthemoff** [comment]
Thanks 😊
