### ISSUE TITLE
[BUG/ISSUE] Dualsense emulation gamepad not responding and having random inputs

### ISSUE THREAD

**Issue by GuckicheLorraine** [Paliverse/DSX#30]
**Describe the bug** After 30 mins of playing Sonic Frontiers with DS emulation and controller plugged in while using haptic rumble,  the controller stopped reacting to my inputs and start to give some random inputs

**To Reproduce**
1. Use DS emulation
2. Wait for it

**Comment by popthemoff** [comment]
I'm guessing that this is now fixed with the driver update?
