### ISSUE TITLE
[BUG/ISSUE] weird bug when DSX opens while dueslense firmware updater is running 

### ISSUE THREAD

**Issue by Execrit** [Paliverse/DSX#31]
**Describe the bug**
DSX stuck on checking ownership while duelsense firmware updater is running. after closing the updater its stuck on finding a new VIGEM driver for a long time, then saying I dont have it at all (even though I have)
**To Reproduce**
1. open duelsense firmware updater 
2. run DSX
3. if its stuck on checking ownership you need to close the duelsense firmware updater
![image](https://github.com/Paliverse/DSX/assets/92687769/54bf14f1-e829-426b-8c51-b3968fa2feeb)

after launching the VIGEM installer thing, it crashed and then dsx restarted and suddenly stuff worked

**Comment by popthemoff** [comment]
A Title to both your bug reports would be helpful

**Comment by Paliverse** [comment]
Tested same scenario on my end with no issues. Maybe something with the servers that fetches info.
