### ISSUE TITLE
[BUG/ISSUE] CPU Usage increases when using the application causing in-game performance to fluctuate

### ISSUE THREAD

**Issue by Sceidge** [Paliverse/DSX#40]
DSX causing performance issues in-game and causing CPU usage to be higher than usual.

**Comment by Paliverse** [comment]
Need more details, can’t really do anything with that info.

what were you doing within DSX, which emulation was active, which physical controller was connected? Etc.. so many different scenarios and possibilities to pinpoint an issue.

**Comment by Paliverse** [comment]
Closing due to no further feedback or others mentioning this issue.

Either way, DSX v3 still needs optimization which will happen over time.
