### ISSUE TITLE
Audio haptics strength 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#41]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] Audio haptics strength is kinda weak

**Describe the solution you'd like**
A way to boost audio haptics strength, I have volume at 100% Also some people with different audio setups won't be able to use windows audio at 100% making it too loud, so decreasing audio makes haptics even weaker.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. I'm wondering if there could be a kind of EQ mixer/booster 

**Additional context**

**Comment by Paliverse** [comment]
Will investigate this, but i don't think anything can be done since the way Audio Haptics works is looping the audio being sent to the main Sound device and sending it to the DualSense. Will see if i can adjust it

**Comment by popthemoff** [comment]
I think something like Voice Meeter would do this. So it's not a big issue. You can boost the dB and frequency. Might be something to experiment with in the future when the core components are in place
