### ISSUE TITLE
[BUG/ISSUE] Controller constantly vibrates after about a minute

### ISSUE THREAD

**Issue by XDanfr** [Paliverse/DSX#43]
I use the controller for a while and it just, constantly vibrates. Any emulation, either rumble or rumble to haptics.

**To Reproduce**
1. Connect controller and open DSX Alpha
2. Choose rumble or rumble to haptics
3. Open game and let it rumble a bit
4. Constant vibration

**Comment by Paliverse** [comment]
This issue should be resolved with the latest DSX v3 version and the latest VirtualPad driver. If it’s still occurring reopen this issue.
