### ISSUE TITLE
[BUG/ISSUE] The first launch 

### ISSUE THREAD

**Issue by mfantastic8** [Paliverse/DSX#50]
On the initial window, when I first opened v3, it showed that I did not have .NET and ASP.NET installed. A button at the bottom suggested installing .NET. When I installed it and it remained to install ASP.NET, the name of the bottom button did not change. It still said "Install .NET DESKTOP".

1. Do not have the necessary libraries installed
2. Install .NET DESKTOP first
3. See the bug itself

**Comment by Execrit** [comment]
you need to restart after installing the .net

**Comment by popthemoff** [comment]
Did you get this working, someone who just got alpha is stuck in a loop

**Comment by Paliverse** [comment]
Closing due to no further info.
