### ISSUE TITLE
Adaptive Triggers Passthrough DualSense Edge

### ISSUE THREAD

**Issue by andria-dev** [Paliverse/DSX#51]
## Bug Description
Adaptive Triggers Passthrough for DualSense Edge does not appear to be working.

## Steps to Reproduce
Reproduce the behavior with the following steps:
1. Plug in a Dual Sense Edge controller.
2. Switch to Dual Sense Emulation.
3. Make sure that Adaptive Triggers Passthrough is enabled.
4. Start up a game like COD MW2 and make sure that Trigger Effects is set to Full Haptics.
5. Try shooting any gun, and see that no adaptive trigger data was applied to the controller.

**Comment by Paliverse** [comment]
Does this still fail to work?

**Comment by andria-dev** [comment]
Yes, @Paliverse. The Adaptive Triggers Passthrough still does not appear to work with the DualSense Edge controller on any games that I know of that support Adaptive Triggers including COD MW2. Tested it again today.

**Comment by andria-dev** [comment]
@Paliverse Update: it actually seems to work perfectly with _Ratchet & Clank: Rift Apart_ (tested today). Unfortunately, it still isn't working with COD MW2, and I'm not sure why. I assume the issue isn't on the COD developers' side though since I've heard people online say that it worked for the regular DualSense.

I recently came across this [list of games that support Adaptive Triggers and Haptic Feedback](https://www.pcgamingwiki.com/wiki/Controller:DualSense#Games_with_adaptive_trigger_and_haptic_feedback_support). I might try some more games from this list.
