### ISSUE TITLE
[BUG/ISSUE] LED bug 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#55]
**Describe the bug** Xbox emulation showing one player led even though it's not selected as on in the led menu

**To Reproduce**
1. 
2. 
3.

**Comment by Paliverse** [comment]
This isn't so much as a bug, more of that some other program like steam sends info, i can see the same thing happen.

This is due to the new change where DSX sends data to the controller when there's a new change from the previous state.

Maybe ill add an option to always send to the controller.
