### ISSUE TITLE
[BUG/ISSUE] DSX UI dissapearing after coming back from tray

### ISSUE THREAD

**Issue by Execrit** [Paliverse/DSX#56]
**Describe the bug**
It doesnt always happen, but sometimes when clicking on dsx while its in tray, every UI element I hover over becomes black

sometimes it happens after I have another bug that makes DSX appear twice in tray, then when clicking one of the DSX icons the app comes to life, and when clicking the other dsx in tray a dsx window pops up with the problem I described.
**To Reproduce**
1. put dsx in tray
2. try to open it (sometimes it works normally and sometimes it doesnt)
3. make a tasty peanut butter sandwich
![image](https://github.com/Paliverse/DSX/assets/92687769/613ff052-7316-4ce7-970e-a332f78d6a2d)

**Comment by Paliverse** [comment]
This should be fixed
