### ISSUE TITLE
[BUG/ISSUE] shortcut menus dissapearing

### ISSUE THREAD

**Issue by Execrit** [Paliverse/DSX#63]
**Describe the bug**
title
**To Reproduce**
1. go to shortcuts
2. select a button
3. click on windows shortcut presets and start abusing the hell out of your scrolling wheel
![image](https://github.com/Paliverse/DSX/assets/92687769/69041d36-fdd7-49ea-9ba6-66abb8c937f8)

**Comment by Paliverse** [comment]
Duplicate of other posts
