### ISSUE TITLE
[BUG/ISSUE] weird scrolling issues

### ISSUE THREAD

**Issue by Execrit** [Paliverse/DSX#65]
**Describe the bug**

**To Reproduce**
1. go to shortcuts
2. scroll (try to put your mouse where I put it)
3.
when it stops scrolling for a few seco

nds, its because of the bug

https://github.com/Paliverse/DSX/assets/92687769/4ea5d52f-c3ed-4e74-9ac9-f2b6c01b3b08

**Comment by popthemoff** [comment]
I had same issue this morning but didn't report 👍

**Comment by Paliverse** [comment]
Unable to reproduce. No one else is reporting this isssue. Closing for now.
