### ISSUE TITLE
[ISSUE] XBOX emulator Left stick have outbtn dead

### ISSUE THREAD

**Issue by C147ArmoredCat** [Paliverse/DSX#74]
**Describe the bug**

**To Reproduce**
1. only xbox emulator have this issue
2. left stick
3.out btn dead
![image](https://github.com/Paliverse/DSX/assets/18070045/fac6f044-4d85-4979-98bb-4afbc65e9ed6)

![image](https://github.com/Paliverse/DSX/assets/18070045/32c5df12-c79e-4078-b39a-4c2255c5b31f)

**Comment by Paliverse** [comment]
Sticks are currently pass throughs, so whatever the controller reports to DSX, is what is being sent to the virtual controller.
