### ISSUE TITLE
[BUG/ISSUE] lightbar brightness not working on breathing or strobing setting 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#75]
**Describe the bug**  select breathing or strobing and light bar brightness is ineffective 

**To Reproduce**
1. 
2. 
3.

**Comment by popthemoff** [comment]
Will you be adding LED off button, rather than rely on changing brightness?

**Comment by Paliverse** [comment]
Fixed in Alpha 112, for completely disabling the lightbar, there was some issues where the controller needed to be restarted when going to a different mode.  For now the brightness control will have to do.
