### ISSUE TITLE
[BUG/ISSUE] Button mapping 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#77]
X to R2 & L2 NOT SHOWING IN GAMEPAD TESTER  

Update, I think it's any button mapped to those keys.  We need more people to test button mapping with gamepad tester because it's showing in gamepad UI as pressed

**To Reproduce**
1. 
2. 
3.

**Comment by popthemoff** [comment]
It's working again now, after resetting profile

**Comment by Paliverse** [comment]
Fixed in Alpha 114

**Comment by popthemoff** [comment]
Thanks
