### ISSUE TITLE
[BUG/ISSUE]

### ISSUE THREAD

**Issue by crunchpac** [Paliverse/DSX#9]
VIRTUAL CONTROLLER - polling rate is very odd its acting like its polling rate locked but hit some low numbers
its doing a pattern 7ms then 0.01ms occasionally spiking to 20-30ms and trigger deadzones also dont seem to work for it also im not getting input from the touchpad

**Comment by Paliverse** [comment]
No notice of issues with pollng rate as DSX doesn't control it at all. It reads as fast as it could.
