### ISSUE TITLE
[BUG/ISSUE] bluetooth driver error

### ISSUE THREAD

**Issue by pablo5425** [Paliverse/DSX#92]
turning on/off bluetooth on windows settings while DSX is running can cause a driver error, making bluetooth devices stop working

1. launch DSX v3 with bluetooth on
2. connect at least 1 controller and let DSX grab it
4. enter windows settings and disable bluetooth
5. enable bluetooth again. all paired devices will display "driver error"

current workaround: exit DSX, then turn bluetooth on again. driver error will disappear
![image](https://github.com/user-attachments/assets/397fa3ed-8625-45e5-8dfe-418aaf93e9fe)

**Comment by Paliverse** [comment]
DSX v3.1 improves on this. Should happen less frequently. Once the Device Manager System is improved, and that controllers are disposed of properly within DSX, this issue will be gone for good. I would expect this change to be in v3.2.
